name: Playwright Tests
on:
  push:
    branches: [ duckduckgo ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net6.0/playwright.ps1 install --with-deps     
    - name: Ensure LivingDoc CLI is installed
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI  
    - name: Run your tests
      run: dotnet test  
    - name: GenerateLivingSpec
      run: livingdoc test-assembly bin/Debug/net6.0/PlaywrightSpecFlowPOM.dll -t bin/Debug/net6.0/TestExecution.json -o MyTestResults.html	  
    - name: Upload LivingDoc report
      id: artifact-upload-step
      uses: actions/upload-artifact@v2
      with:
        name: My Test Results
        path: MyTestResults.html
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Output artifact URL
      run: "Artifact URL: https://github.com/${{ github.run_id }}/actions/runs/${{ steps.artifact-upload-step.outputs.artifact-id }}#artifacts"
