name: Playwright Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - uses: actions/cryptic-wizard/run-specflow-tests@v1.3.3
      with:
        test-assembly-path: PlaywrightSpecFlowPOM/bin/Release/net7.0
        test-assembly-dll: PlaywrightSpecFlowPOM.dll
        output-html: MyTestResults.html
